# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04", "ubuntu-22.04"]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          swig \
          xmlsec1 \
          libengine-pkcs11-openssl \
          libsofthsm2 \
          softhsm2 \
          opensc
        sudo mkdir -p /var/lib/softhsm/tokens

    - name: Initialize SoftHSM2 token
      run: |
        mkdir -p ~/.config/softhsm2
        echo "directories.tokendir = /var/lib/softhsm/tokens" > ~/.config/softhsm2/softhsm2.conf
        sudo softhsm2-util --init-token --slot 0 --label "test" --pin 1234 --so-pin 1234

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip uninstall -y xmlsec || true
        pip install coveralls importlib_resources
        pip install .[test]

    - name: Run coverage
      run: |
        python -m coverage run --source=xmlsec -m nose2 -vv
      env:
        XMLSEC_SKIP_P11: "1"

    - name: Run coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m coveralls
